---
- name: Calling Groovy script {{ script_name }}
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script/{{ script_name }}/run"
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pw }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    timeout: "{{ nexus_script_timeout }}"
    force_basic_auth: yes
    body: "{{ args | to_json }}"
