---
- name: Check generated files exist
  stat:
    path: "{{ nexus_data_dir }}/admin.password"
  register: passwd_exist
  ignore_errors: yes

- name: Get generated admin password from file (nexus >= 3.17)
  block:
    - name: Slurp content of remote generated password file
      slurp:
        src: "{{ nexus_data_dir }}/admin.password"
      register: _slurpedpass

    - name: Set default password from slurped content
      set_fact:
        nexus_generated_admin_password: "{{ _slurpedpass.content | b64decode }}"
  when: passwd_exist.stat.exists == true

- name: Declaring Groovy script change_admin_pw
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script"
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_generated_admin_password }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    body:
      name: "change_admin_pw"
      type: 'groovy'
      content: "security.securitySystem.changePassword('admin', args)"
  when: passwd_exist.stat.exists == true

- name: Calling Groovy script change_admin_pw
  vars:
    change_pw_script: "/service/rest/v1/script/change_admin_pw"
  uri:
    url: "http://localhost:{{ nexus_port }}{{ change_pw_script }}/run"
    user: "{{ nexus_default_admin_user }}"
    password: "{{ nexus_generated_admin_password }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    force_basic_auth: yes
    body: "{{ nexus_admin_pw }}"
  when: passwd_exist.stat.exists == true

- name: Clear generated password file from install (nexus > 3.17)
  file:
    path: "{{ nexus_data_dir }}/admin.password"
    state: absent
  when: passwd_exist.stat.exists == true
