---
- name: Removing (potential) previously declared Groovy script {{ item }}
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script/{{ item }}"
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pw }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204,404

- name: Declaring Groovy script {{ item }}
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script"
    user: "{{ nexus_admin_user }}"
    password: "{{ nexus_admin_pw }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    body:
      name: "{{ item }}"
      type: 'groovy'
      content: "{{ lookup('file', 'groovy/' + item + '.groovy') }}"
