---
- name: Check if we need to fallback to the default password
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script"
    force_basic_auth: yes
    user: "{{ nexus_default_admin_user }}"
    password: "{{ nexus_admin_pw }}"
  register: nexus_login_attempt
  when: nexus_admin_pw != nexus_default_admin_pw
  ignore_errors: yes

- name: Removing (potential) previously declared Groovy script change_admin_pw
  vars:
    change_pw_script: "/service/rest/v1/script/change_admin_pw"
  uri:
    url: "http://localhost:{{ nexus_port }}{{ change_pw_script }}"
    user: "{{ nexus_default_admin_user }}"
    password: "{{ nexus_default_admin_pw }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 204,404
  when: nexus_login_attempt | failed

- name: Declaring Groovy script change_admin_pw
  uri:
    url: "http://localhost:{{ nexus_port }}/service/rest/v1/script"
    user: "{{ nexus_default_admin_user }}"
    password: "{{ nexus_default_admin_pw }}"
    body_format: json
    method: POST
    force_basic_auth: yes
    status_code: 204
    body:
      name: "change_admin_pw"
      type: 'groovy'
      content: "security.securitySystem.changePassword('admin', args)"
  when: nexus_login_attempt | failed

- name: Calling Groovy script change_admin_pw
  vars:
    change_pw_script: "/service/rest/v1/script/change_admin_pw"
  uri:
    url: "http://localhost:{{ nexus_port }}{{ change_pw_script }}/run"
    user: "{{ nexus_default_admin_user }}"
    password: "{{ nexus_default_admin_pw }}"
    headers:
      Content-Type: "text/plain"
    method: POST
    status_code: 200,204
    force_basic_auth: yes
    body: "{{ nexus_admin_pw }}"
  when: nexus_login_attempt | failed
