---
- name: Prepare
  hosts: all
  become: true
  collections:
    - devops.devops_ci_cd_collection
  pre_tasks:
    - name: Install needed packages from APT repository
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jre
        - openjdk-8-jdk
  roles:
    - role: ansible_role_nexus
      vars:
        nexus_repos_helm_hosted:
          - name: boat
        nexus_repos_conan_hosted:
          - name: barbarian
        nexus_repos_pypi_hosted:
          - name: slytherin
            version_policy: release
            write_policy: allow
          - name: pypi-internal
            version_policy: release
            write_policy: allow
        nexus_repos_npm_hosted:
          - name: npm-internal
            blob_store: default
          - name: noodle
            blob_store: default
          - name: foo
            blob_store: default
        nexus_blob_stores:
          - name: test
            path: test
        nexus_repos_npm_group:
          - name: npm-public
            blob_store: default
            member_repos:
              - noodle
              - foo
        nexus_repos_maven_hosted:
          - name: maven-foobar
          - name: private-release
            version_policy: release
            write_policy: allow_once
        nexus_repos_docker_hosted:
          - name: docker-hosted
            http_port: 9080
            v1_enabled: True
          - name: docker-foobar
        nexus_repos_maven_proxy:
          - name: central
            remote_url: 'https://repo1.maven.org/maven2/'
            layout_policy: permissive
          - name: jboss
            remote_url: 'https://repository.jboss.org/nexus/content/groups/public-jboss/'
        nexus_repos_maven_group:
          - name: public
            member_repos:
              - central
              - jboss
        nexus_repos_raw_hosted:
          - name: raw-internal
            version_policy: release
            write_policy: allow_once
        nexus_repos_conan_proxy:
          - name: 'conan-center'
            remote_url: 'https://bintray.com/conan/conan-center'
          - name: 'bincrafters'
            remote_url: 'https://bintray.com/bincrafters/public-conan'
          - name: 'conan-community'
            remote_url: 'https://bintray.com/conan-community/conan'
        nexus_repos_cleanup_policies: []
