---
galaxy_info:
  role_name: ansible_role_jenkins_slave
  author: "Laszlo Beres"
  description: "Deploy Nexus 3 OSS Repository Service"
  license: "GPL-2.0-or-later"
  min_ansible_version: '7.6.0'
  galaxy_tags: []
  platforms:
    - name: Ubuntu
      versions:
        - focal
dependencies: []
